### ISSUE TITLE
Relive in voctoweb [EPIC]

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctoweb#421]
media.ccc.de hat seit letztem Congress grundsätzlich Support dafür Relive Mittschnitte anzuzeigen, sofern die einzelnen Vorträge (Events) schon in voctoweb angelegt sind.

Ich habe das jetzt noch so erweitert, das bei leeren Image URLs, die Thumbnails aus dem Relive-Daten genommen werden, vgl. https://github.com/voc/voctoweb/commit/ea81a8c4e3af6c8cb287c2b3c0e62bec9bb75529 – falls dort nichts vorhanden ist, gibt es einen Fallback auf das Konferenzlogo. Letzteres kann in der Konfernzübersicht (z.B. https://media.ccc.de/c/sotm2019) zu Problemen führen,  wenn beim Konferenzloge die Seitenverhältnisse zu sehr von 16:9 abweichen. Sprich da muss eigentlich noch ein `max-width` mit ins CSS.
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/40266/67641108-c65f6400-f8ff-11e9-97a7-f7d3e4d3eefc.png">

Auf voctoweb-Seite sind sonst noch folgende Baustellen offen:
* [x] klären ob Events immer erst zum realen Vortragsbeginn angelegt werden sollen, oder auch schon davor
* [x] noch nicht releaste Events (die nur ein relive recording haben) auf der Startseite ausblenden
* [x] Sollte ein update des Events dafür sorgen das es dort wieder oben angezeigt wird? Gefühlt eher nicht
*  [x] Wenn man sich über die Eventliste zum Relive Player durch klickt wird der Player nicht angezeigt – erst wenn man die Seite einmal refreshed/reloaded. Hat das ggf. etwas mit dem Turbo-Links Addons zu tun?
* [x] Thumbnails beim Relive Player werden nicht richtig angezeigt, siehe https://github.com/voc/voctoweb/issues/420

**Comment by manno** [comment]
> Sollte ein update des Events dafür sorgen das es dort wieder oben angezeigt wird? Gefühlt eher nicht

Eher nicht. `updated_at` wird nicht von allen update Funktionen aktualisiert. Jedoch geht es vermutlich in den cache key ein.

> Wenn man sich über die Eventliste zum Relive Player durch klickt wird der Player nicht angezeigt – erst wenn man die Seite einmal refreshed/reloaded. Hat das ggf. etwas mit dem Turbo-Links Addons zu tun?

[Turbolinks](https://github.com/turbolinks/turbolinks) können wir entweder [auf dem Link ausschalten](https://github.com/voc/voctoweb/commit/a8895e9d46ace503860705ee396ae39931b63ccd) oder das [Javascript des Relive Players anpassen](https://github.com/voc/voctoweb/blob/master/app/assets/javascripts/slider.js#L35-L38). Wenn möglich das JS anpassen, Turbolinks machen die Webseite schnell wie eine Single Page App...
